### ISSUE TITLE
Update chd-rs to 0.1.4

### ISSUE THREAD

**Issue by chyyran** [Manorhos/imageparse#1]
A fairly critical bug in the `LzmaCodec` implementation that would silently return corrupted bytes if `verify_block_crc` was not enabled was fixed in https://github.com/SnowflakePowered/chd-rs/commit/fdb6a7966c86236f1b1d7b8cb68d26c3019274f0 and published as version [0.1.4](https://crates.io/crates/chd/0.1.4). 

This bug was present since https://github.com/SnowflakePowered/chd-rs/commit/63fc6b317acedb4145ea9b298cd2cce31264c131 so all versions since until 0.1.4 have been yanked.

I noticed that you have https://github.com/SnowflakePowered/chd-rs/commit/d9fbd9d pinned in your `Cargo.toml` which is affected by this bug. Please update to `0.1.4` as soon as possible.

I don't think you are using it, but [chd-capi](https://docs.rs/chd-capi/0.1.3/chd_capi/) is not affected since the chd-capi crate specifies any `0.1` version of chd-rs.

**Comment by Manorhos** [comment]
Thanks, done.

Just interested, did you find any real-world examples of the corruption bug being triggered?
I tried out a bunch of PS1 games using this crate and didn't notice anything weird.

**Comment by chyyran** [comment]
I had a test CHD of [Alien Trilogy (EUR)](http://redump.org/disc/882/) (SLES-00101) that I was working with to test and the extracted raw data differed by one byte. I did a bisect and discovered the lzma-rs refactoring changes in https://github.com/SnowflakePowered/chd-rs/commit/63fc6b317acedb4145ea9b298cd2cce31264c131 didn't set the unpacked size properly after resetting the decoder.

**Comment by Manorhos** [comment]
Ah okay, thanks!
