### ISSUE TITLE
I believe this code should be deleted

### ISSUE THREAD

**Issue by i30817** [Manorhos/imageparse#5]
https://github.com/Manorhos/imageparse/blob/db40019b0845ae25878164427e3537daa03bd6b1/src/chd.rs#L116

the 'parent' you're doing in the recursive function already includes the original file, since it's sent there for the 1rst call (in both branches, the base case and not), so this one is just additional pointless indirection (and might return a error from chd-rs too). If i'm not mistaken.

**Comment by i30817** [comment]
I also have a question, there is a error in the library called 'TrackParseError':

https://github.com/Manorhos/imageparse/blob/658515e3ac573ca1b48a53a9825775fc31120f0f/src/chd.rs#L47

What returns this? I can't find creation of it or 'text_io::Error' on the github search.

**Comment by Manorhos** [comment]
Oh, you're right, the child file is finally opened with itself as the parent followed by the other parents, interesting that that works with no issues.

`text_io::Error` can be returned by this function: https://github.com/Manorhos/imageparse/blob/658515e3ac573ca1b48a53a9825775fc31120f0f/src/chd/track_metadata.rs#L72
